porybox/porybox

- package.json
- test/unit.js
Fixes #40
(I saw that you had self-assigned this issue, but I wanted to figure out the sails.request thing so we that can use it for most of the future tests. Feel free to reject/add to this PR if you had other plans for this issue.)
> Added unit test file

- .eslintrc
- api/.eslintrc
- client/.eslintrc
It can be a bit annoying to keep track of the globals in the rc file, but I think it's worth it overall.
> Added no-undef rule to linter

- package.json
- test/controller/auth.js
Now we can actually test things without always getting redirected to the login page.
> Fixed serverside testing

- api/controllers/AuthController.js
- api/controllers/HomeController.js
- api/policies/passport.js
- test/bootstrap.test.js
- test/controller/auth.js
And add some more auth tests.
Fixes #55
> Fix issue with registration

- README.md
- config/local.example.js
> Add installation info to the readme

- api/.eslintrc
- api/controllers/BoxController.js
- api/controllers/HomeController.js
- api/controllers/PokemonController.js
- api/controllers/UserController.js
- api/services/CatchAsyncErrors.js
About 80% of this diff is whitespace, and the rest is basically repetitive stuff. I recommend using [github's no-whitespace diff](/porygonco/porybox/pull/75/files?w=).
The explanation of the actual change can be found [here](https://github.com/porygonco/porybox/blob/d4109ad1f8c979157c6f4cca774ad0ac66120b24/api/services/CatchAsyncErrors.js#L1).
> Remove try/catch boilerplate for async functions

- api/controllers/UserController.js
- config/policies.js
- config/routes.js
- test/controller/auth.js
This bit is obviously pretty important security-wise, so hopefully I didn't mess anything up.
Builds off of #76, so look at that first.
> Add support for changing passwords

- api/controllers/AuthController.js
- test/controller/auth.js
> Redirect /login to / when already logged in

- api/controllers/AuthController.js
- client/userMenu/user.ctrl.js
- client/userMenu/user.module.js
- client/userMenu/user.spec.js
- client/userMenu/user.view.html
- config/policies.js
- config/routes.js
- test/controller/auth.js
> Change logout endpoint to POST request

- api/controllers/HomeController.js
- client/add/add.ctrl.js
- client/add/add.module.js
- client/add/add.spec.js
- client/add/add.view.html
- client/add/pokemon.ctrl.js
- client/add/pokemon.spec.js
- client/add/pokemon.view.html
- client/app.js
- client/header.ejs
- client/layout.ejs
- client/styles/importer.less
- package.json
I should probably add some more tests, and there's a few UI things that need done, but we can probably merge as is just now and I'll do another PR for that, if you are happy.
> Initial pokemon upload working.

- client/styles/importer.less
> Better upload button

- .eslintrc
- client/add/add.module.js
- client/app.js
- client/box/box-card.view.html
- client/box/box-list.view.html
- client/box/box.ctrl.js
- client/box/box.module.js
- client/home/home.module.js
- client/home/index.view.html
- client/home/view.ejs
- client/layout.ejs
- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.module.js
- client/pokemon/pokemon.spec.js
- client/styles/importer.less
- package.json
> Add initial box view, with pokemon cards.

- api/controllers/HomeController.js
- client/home/faq.ejs
- config/policies.js
- config/routes.js
We should probably put something substantive on this page later, but the PR makes it so the page itself is viewable.
> Add placeholder for FAQ page

- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon.ctrl.js
- client/styles/importer.less
Red for the increased stat, blue for the decreased stat.
Feel free to edit if there's a better way to implement it.
> Add colors for increased/decreased stat IVs

- client/static/about.ejs
- client/static/extracting-pk6-files.ejs
- client/static/faq.ejs
- client/static/how-to-pk6-1-bvs.ejs
- client/static/how-to-pk6-2-homebrew.ejs
- client/static/how-to-pk6-3-4-save-files.ejs
- client/static/how-to-pk6-6-decrypted-powersaves.ejs
- client/static/privacy-policy.ejs
- client/static/tos.ejs
Initial pk6 documentation + the usual about/FAQ/ToS/PP pages.
> Documentation

- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.spec.js
This converts the 3DS custom characters (used in nicknames, etc.) into similar unicode alternatives.
> Parse the custom 3DS unicode characters properly

- client/box/box-list.view.html
- client/box/box.ctrl.js
- client/errors/403.ejs
- client/errors/403.html
- client/errors/404.ejs
- client/errors/404.html
- client/errors/500.ejs
- client/errors/500.html
- client/header.ejs
- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
> Display error images when navigating the site

- client/static/about.ejs
- client/static/faq.ejs
> Updating docs

- package.json
...until the issue in #207 is fixed.
> Temporarily lock karma-mocha to v1.0.x

- client/login/login-page.view.html
Makes the login page not look like this on mobile: http://i.imgur.com/vEn6m9x.jpg
> Responsive login

- client/static/how-to-pk6-2-homebrew.ejs
The most important update to the entire project.
> Documentation update

- client/home/index.view.html
Just to have something for now.
> Initial homepage

- package.json
beep boop I'm not actually greenkeeperio-bot
> Chore: Update pk6parse to version 0.10.3 🚀

- client/box/box-card.view.html
- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon-full.view.html
- client/static/about.ejs
- client/static/extracting-pk6-files.ejs
- client/static/faq.ejs
- client/static/how-to-pk6-1-bvs.ejs
- client/static/how-to-pk6-2-homebrew.ejs
- client/static/how-to-pk6-3-4-save-files.ejs
- client/static/how-to-pk6-6-decrypted-powersaves.ejs
- client/static/privacy-policy.ejs
- client/static/tos.ejs
- client/styles/importer.less
> Trying some styling

- api/controllers/BoxController.js
- test/controller/box.js
> Don't throw errors when multiple deletion requests are sent

- client/layout.ejs
- client/pokemon/pokemon-edit.ctrl.js
- client/pokemon/pokemon-edit.view.html
- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.module.js
- client/pokemon/pokemon.spec.js
- client/styles/importer.less
This does not have moving to another box, nor editing of notes (notes are not currently shown on the pokemon view, so it would be silly to be able to edit them).
> Pokemon edit

- api/models/Box.js
- api/models/PokemonNote.js
- api/services/Constants.js
- api/services/Validation.js
- test/controller/box.js
- test/controller/pokemon.js
fixes #224 
* Box name max length: 300 chars
* Box description max length: 1000 chars
* Pokemon note max length: 1000 chars
> Add length limits for box names/descriptions and note text

- api/services/Validation.js
- api/services/protocols/local.js
- client/login/login.ctrl.js
- test/controller/auth.js
> Ensure that the correct error message gets sent on account registration

- client/pokemon/pokemon-full.view.html
> Display "no next level" for level 100 Pokémon

- config/http.js
It doesn't do anything and it adds a bit of bandwidth overhead to server responses.
> Get rid of the x-powered-by header

- client/login/login.view.html
> Prevent LastPass from marking the login form as insecure

- client/pokemon/pokemon.ctrl.js
> Extend toast timeout to 10 seconds

- api/controllers/PokemonController.js
- api/models/Box.js
- api/models/Pokemon.js
- api/models/User.js
- api/services/BoxOrdering.js
- api/services/Constants.js
- api/services/PokemonHandler.js
- api/services/Validation.js
- config/policies.js
- config/routes.js
- test/controller/pokemon.js
Fixes #221
~~This isn't ready to be merged yet~~, but thought I'd leave it here so that the API can be used from the client.
To do:
> Multi upload

- client/layout.ejs
> Add analytics tracking code

- client/pokemon/pokemon-full.view.html
- client/styles/importer.less
There was also a stray leftover pokeapi image fixed in here.
> Display memory text

- client/add/pokemon.view.html
- client/styles/importer.less
Adds a quick link to the documentation at the bottom of the upload dialog.
It's not that pretty, but it'll do for now.
> Add quick link to how2pk6 in upload dialog

- client/pokemon/pokemon-edit.ctrl.js
- client/pokemon/pokemon-edit.view.html
- client/pokemon/pokemon-full.view.html
- client/pokemon/upload-info.view.html
- client/styles/importer.less
- Public and private notes can be viewed and edited
- Hidden data specifies it's viewable only to user when not public
- "LA coming soon"
- some e -> é
> Improve full view

- client/box/box.ctrl.js
- client/layout.ejs
- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon-full.view.html
- client/styles/importer.less
- Footer now properly sits at bottom of page EVEN IN SAFARI !!!
- TM/HM as held item shows icon properly in boxes (fixes #261)
- Public icon is now a globe
> Fix CSS bugs and change Public icon

- api/models/Box.js
- api/services/PokemonHandler.js
- test/controller/box.js
> Send the updatedAt box tag to the box owner

- client/app.js
- client/box/box-list.view.html
- client/box/box.ctrl.js
- package.json
> Make cards draggable

- client/app.js
- client/box/box-list.view.html
- client/box/box.ctrl.js
- package.json
Reverts porygonco/porybox#265
This is making it hard to scroll on mobile at the moment.
> Revert "Make cards draggable"

- client/add/add.ctrl.js
- client/add/add.module.js
- client/add/add.spec.js
> Show toast when pokemon are uploaded

- api/controllers/BoxController.js
- api/services/Constants.js
- client/add/add.ctrl.js
- client/app.js
- client/box/box-list.view.html
- client/box/box.ctrl.js
- client/box/box.module.js
- client/box/box.spec.js
- client/styles/importer.less
- package.json
- test/controller/box.js
- test/controller/pokemon.js
(don't merge yet)
This makes the changes to paginate boxes serverside rather than sending everything at once, which will be necessary to prevent people from crashing our server with large boxes.
To do:
> Box pagination

- client/styles/importer.less
because http://i.imgur.com/uz3f0J7.png
> Change line height for mini cards to em to fix display on Firefox

- client/app.js
- client/box/box-list.view.html
- client/box/box.ctrl.js
- client/pokemon/pokemon-card.view.html
- client/styles/importer.less
- package.json
There is now a button in the toolbar to enable dragging.
To do:
> Toggleable dragging

- client/add/add.ctrl.js
- client/add/add.module.js
- client/add/add.spec.js
- client/app.js
- client/box/box.ctrl.js
- client/box/box.module.js
- client/box/box.spec.js
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.module.js
- client/pokemon/pokemon.spec.js
- client/profile/profile.ctrl.js
- client/profile/profile.module.js
This pops up a toast at the bottom of the screen for unexpected errors (in addition to logging the errors to the console).
fixes #259
> Add a generic error handler for unexpected errors

- api/policies/passport.js
- client/layout.ejs
This will ensure that we can avoid bundle cache issues by bumping the version number.
> Include the version number in the request for the bundle files

- client/app.js
- client/prefs/prefs.ctrl.js
- client/prefs/prefs.module.js
- client/prefs/prefs.view.html
- client/styles/importer.less
- client/userMenu/user.view.html
> Add a form for changing passwords

- client/app.js
- client/box/box.ctrl.js
> Update `main.boxes` when a box is changed

- client/add/add.ctrl.js
> Ensure boxes never have 0 pages

- client/add/box.ctrl.js
Not exactly the most elegant solution, but it works for now since preferences can't be changed yet anyway.
> Make the default box visibility 'listed'

- api/controllers/PokemonController.js
- test/controller/pokemon.js
> Ensure multiple deletions of the same thing don't cause errors

- LICENSE.md
Seems like we forgot to add a license file until now.
To avoid complications later on, it would be good if everyone who has contributed could comment here saying that they're okay with adding this.
@NotRaia @YaManicKill @TheSonAlsoRises @SnowPhoenix @Kirzi
> Add Apache license

- client/add/add.ctrl.js
- client/pokemon/pokemon.ctrl.js
- client/prefs/prefs.ctrl.js
Having toasts in the top right prevents you from being able to click on the links in the nav bar until they go away, which is annoying.
> Move top right toasts to bottom right

- api/controllers/PokemonController.js
- client/add/add.ctrl.js
- client/app.js
- client/layout.ejs
- client/pokemon/pokemon.ctrl.js
- client/prefs/prefs.ctrl.js
- client/static/how-to-pk6-2-homebrew.ejs
- client/static/how-to-pk6-3-4-save-files.ejs
- client/styles/importer.less
- package.json
- test/controller/pokemon.js
Branch for the next release of porybox. Let's make PRs for features/non-urgent bugfixes onto this branch, and then merge all of it onto master when we're ready to release.
> v1.0.0-beta2

- client/app.js
- client/layout.ejs
> Prevent box names from being html-escaped twice

- api/policies/passport.js
- config/views.js
> Ensure that the `VERSION` view local is included even in error responses

- api/policies/passport.js
- client/app.js
- client/layout.ejs
- config/views.js
- package.json
Branch for the next release of porybox. Let's make PRs for features/non-urgent bugfixes onto this branch, and then merge all of it onto master when we're ready to release.
> v1.0.0-beta3

- client/pokemon/pokemon-card.view.html
> Add angular one-time bindings to pokemon cards

- client/box/box-list.view.html
> Compute card centers on the x-axis rather than the y-axis when dragging

- client/login/register.view.html
> Make it clear that emails are not public + swap with username field

- client/pokemon/pokemon-full.view.html
> Arrange relearnable moves to be 2x2 instead of in one row

- api/controllers/UserController.js
- test/controller/user.js
> Don't throw a 500 error when a user profile isn't found

- client/add/pokemon.ctrl.js
- client/add/pokemon.view.html
> Allow multiple pk6 files to be added with the button

- client/profile/profile.ctrl.js
> Handle profile-viewing errors more gracefully

- client/add/pokemon.view.html
Fixes 306 and just makes it a bit nicer
> Rearrange pokemon upload modal

- client/pokemon/pokemon.ctrl.js
> Move the undelete toast to the bottom right

- client/box/box.ctrl.js
> Fix box deletion

- package.json
Changelog:
* Fixed a bug where boxes couldn't be deleted (#385)
> v1.0.0-beta5

- client/add/add.ctrl.js
- client/box/box-list.view.html
- client/box/box.ctrl.js
- client/box/box.module.js
- client/pokemon/pokemon.ctrl.js
> Add toast for box actions

- client/pokemon/pokemon-edit.view.html
> Don't allow notes over 2000 characters to be entered clientside

- client/account/info.ctrl.js
Seems like adding the no-console thing broke the build after merging, because there was a console statement added in another branch (even though it was valid on its own).
> Fix the build

- api/models/Pokemon.js
- api/services/PokemonHandler.js
- client/pokemon/pokemon-full.view.html
- client/styles/importer.less
- test/controller/box.js
- test/controller/pokemon.js
> Display the "back to box" button if the box is listed

- client/box/box.ctrl.js
> Make sure the loading icon disappears after the box page is done loading

- package.json
We should probably do some QA with this before we merge it, but I figured I'd create the changelog anyway.
Changelog:
* Added a page to set default box visibility and Pokémon visibility (#376)
* Improved feedback for editing and deleting boxes (#388)
* Added infinite scrolling when viewing large boxes (#369)
* Added a 'back to box' button when viewing other users' Pokémon, if the Pokémon are in listed boxes (#395)
* Improved feedback for the login, register, and change-password forms (#393)
* Added password reset functionality (#405)
> v1.0.0-beta6

- package.json
Changelog:
* Fixed an issue where the client would sometimes think that identical inputted passwords did not match if the passwords contained special characters. (#411)
> v1.0.0-beta7

- client/box/box.ctrl.js
> Ensure that scrolling is possible on large screens

- package.json
Changelog:
* Fixed an issue where infinite scrolling in boxes did not work on large monitors (#416)
* Fixed an issue where the loading icon would not disappear in empty boxes
> v1.0.0-beta8

- client/app.js
> Fix login form errors

- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
> Add upload date

- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
- client/styles/importer.less
> Display Hidden Power type, BST, EV total, and download count

- client/static/how-to-pk6-2-homebrew.html
- client/styles/importer.less
The instructions were outdated/inaccurate.
> svdt documentation update

- client/pokemon/pokemon-edit.view.html
- client/styles/importer.less
> Prevent modals from becoming too wide

- client/static/faq.html
- client/static/markdown.html
- client/static/static.module.js
- client/styles/importer.less
- config/routes.js
Fixes #429 
To do:
I am probably not going to touch this in the next couple of days, so feel free to edit/merge at will.
> Initial markdown documentation

- client/add/pokemon.view.html
- client/cloneList/cloneList.view.html
- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon-full.view.html
- client/static/faq.html
- client/styles/importer.less
This should help people learn what the icons mean.
> Display icons for Pokémon and box visibility around the site

- package.json
(we should probably do some QA before merging)
Changelog:
* Decrypted save files can now be uploaded to Porybox directly.
* If a Pokémon is not unique on the Porybox database, you can now view a list of its duplicates.
* You can now change your email address from your account settings.
* Public/private notes on a Pokémon are now rendered with Markdown.
* The Hidden Power type, base stat total, and EV total of a Pokémon are now viewable on its summary page.
* The upload date and download count of a Pokémon are now viewable on its "Upload info" page.
* Unlisted boxes are now displayed with a lock icon to distinguish them from listed boxes.
> v1.0.0-beta9

- client/pokemon/pokemon-full.view.html
> Don't display - for IVs of 0

- client/pokemon/pokemon.ctrl.js
> Correctly display item images that contain multiple spaces

- client/box/box.ctrl.js
- client/cloneList/cloneList.ctrl.js
fixes #462 
Due to https://github.com/balderdashy/sails.io.js/issues/54, parameters in sails.io.js requests do not actually get appended to the querystring.
> Ensure that parameters in client requests are sent in the querystring

- package.json
> v1.0.0-beta10

- client/add/add.spec.js
- client/add/pokemon.spec.js
- client/box/box.spec.js
- client/login/login.spec.js
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.spec.js
- client/userMenu/user.spec.js
This fixes the clientside tests (which hadn't been running for a little while due to a stray `it.only` test), and also fixes #472.
> Fix clientside tests and images

- config/http.js
- test/controller/auth.js
> Allow form submission to paypal.com

- client/styles/importer.less
Fixes [this issue](https://www.reddit.com/r/porybox/comments/503yzw/august_28th_2016_update_v100beta11/d711kpv)
> Import angular-csp.css to prevent angular from using inline scripts

- api/controllers/BoxController.js
- api/controllers/PokemonController.js
- api/models/Box.js
- api/services/Constants.js
- api/services/PokemonHandler.js
- test/controller/box.js
- test/controller/pokemon.js
> Add a size cap for boxes

- api/controllers/BoxController.js
- api/controllers/PokemonController.js
- api/models/Pokemon.js
- api/services/PokemonHandler.js
- test/controller/box.js
- test/controller/pokemon.js
Just need to fix the tests for the list of clones. But it's too late at night for that.
> Don't show pokemon that are in unlisted boxes in the list of clones.

- config/http.js
- test/controller/auth.js
For more info on the bug, see [here](/not-an-aardvark/ios-csp-test).
> Add a workaround for the iOS 10 CSP bug

- package.json
I have no idea why this one never got a PR created for it.
> chore(package): update sails.io.js to version 0.14.0

- client/add/pokemon.ctrl.js
- client/add/pokemon.view.html
> Add warning when uploading public pokemon

- api/controllers/UserController.js
- api/services/EmailTemplates/forgottenUsername.ejs
- client/forgotPassword/forgotPassword.ctrl.js
- client/forgotPassword/forgotPassword.view.html
- client/login/login.view.html
- config/policies.js
- config/routes.js
- test/controller/user.js
> Add lost username endpoint

- client/pokemon/pokemon.ctrl.js
> Don't send a move request if the box doesn't change

- client/add/pokemon.view.html
- client/styles/importer.less
> Fix upload buttons not appearing in Safari

- package.json
See https://github.com/porygonco/porybox/pull/624
> Prevent greenkeeper from updating nodemailer

- CONTRIBUTING.md
- README.md
- api/models/Pokemon.js
- client/footer.ejs
- client/static/about.html
- client/static/faq.html
- package.json
porygonco/porybox -> porybox/porybox
> Update links to repository

- client/add/add.module.js
- client/box/box-list.view.html
Fixes #522.
There is probably a prettier way to do this.
> Show indicator/upload button for empty boxes

- client/login/login.view.html
> Changing username allows user to try logging in again

- client/styles/importer.less
> Add the max width for pokemon images.

- client/box/box.ctrl.js
> Add idNo to attributes that we get in box view

- api/models/Pokemon.js
> Fix names being gen 6 specific ones

- client/pokemon/pokemon-full.view.html
> Change "TID" to "ID No." on frontend

- package.json
I got bored of restarting when editing less/css files.
> Add watching to less on start:dev

- .travis.yml
- package.json
- test/bootstrap.test.js
> Use in memory mongo for tests

- client/pokemon/pokemon-full.view.html
> Fix the download link

- client/pokemon/pokemon-full.view.html
> Remove swiping between tabs

- api/models/Pokemon.js
- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.spec.js
> Add fulltid. Hide sid for gen 7

- client/add/add.ctrl.js
- client/add/add.spec.js
- client/box/box-card.view.html
- client/box/box.ctrl.js
- client/home/home.ctrl.js
- client/pokemon/pokemon-icon.view.html
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.module.js
- client/styles/importer.less
> View pokemon sprites on box card

- client/home/home.ctrl.js
> Fix error on homepage

- client/add/pokemon.view.html
> Allow drag/drop of save files not called main

- client/add/parseSaveFile.js
- client/add/pokemon.ctrl.js
> Add Sun/Moon save files

- client/pokemon/pokemon-full.view.html
`Download pk6 file` -> `Download file`
> Rename "download pk6" label

- client/pokemon/pokemon-full.view.html
> Display generation in upload info

- client/styles/boxsprites.less
- client/styles/importer.less
- client/styles/ribbons.less
> Add cache busting to sprite sheets

- api/controllers/PokemonController.js
- api/services/PokemonHandler.js
- client/pokemon/pokemon-full.view.html
Prevents need for extra backward-compatibility code in other places.
> Default gen property to gen 6 when it does not exist

- client/pokemon/pokemon-full.view.html
Should we also move the clone status to the "Upload info" tab in the meantime to avoid having an "Analysis" tab that just has one card and no real analysis?
Vote with 👍/ 👎.
> Remove "Legality analysis coming soon" message
