- test/controller/pokemon.js
I'm not actually sure what effect these have (I'm pretty sure they don't actually do anything), but they're not supposed to be there and we may as well get rid of them for consistency.
> Remove async describe() functions

- api/.eslintrc
- api/controllers/BoxController.js
- api/controllers/PokemonController.js
- api/controllers/UserController.js
- api/models/Box.js
- api/models/DeletedUser.js
- api/models/Passport.js
- api/models/User.js
- api/services/CatchAsyncErrors.js
- api/services/Constants.js
- api/services/Validation.js
- api/services/protocols/local.js
- config/policies.js
- config/routes.js
- test/controller/auth.js
- test/controller/box.js
- test/controller/pokemon.js
- test/controller/user.js
`POST /p/:id/edit`: Edits the meta-properties of a pokemon. Currently `visibility` is the only property that this applies to, but it should be easily scalable if we add more properties. Accepts the properties that should be changed as parameters (e.g. `{visibility: 'private'}`)
`POST /b/:id/edit`: Edits the meta-properties of a box. Currently the properties are `name`, `description`, and `visibility`.
`POST /deleteAccount`: Deletes the authenticated user's account. Requires a `password` parameter, which must be the authenticated user's password.
Fixes #17, fixes #22, fixes #72
> Add editing endpoints

- test/controller/pokemon.js
We update the download count *after* returning a 200 response, since there's no reason to slow down the response time for a side-effect. However, this was causing the tests to occasionally fail because the next request would come in before the download count was finished updating.
(This is causing all our unit tests to fail on travis for some reason, so it would probably be best to merge this before looking at other stuff. I'm not really sure why they're failing consistently now, when they only rarely failed before -- maybe travis changed something internally with database connections.)
> Avoid race conditions in the tests for download counts

- api/controllers/UserController.js
- test/controller/box.js
For instance, on a user's homepage, there's no need to fetch a list of all of their Pokémon in each of the boxes, because we don't display the contents anyway. (Also, sending the data takes up a lot of bandwidth if the user has a lot of stuff uploaded.)
> Avoid sending box content data from a user's box listing

- api/controllers/PokemonController.js
- api/models/Pokemon.js
- package.json
- test/controller/pokemon.js
This way we won't have to send large JSON files to the client in order to map a dex number to a species name, etc.
> Add parsed data such as species names to server responses

- api/services/PokemonHandler.js
`new Buffer()` is deprecated in Node 6; see [here](https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe)
> Replace deprecated `new Buffer()` constructor with `Buffer.alloc()`

- api/.eslintrc
- api/controllers/BoxController.js
- api/controllers/PokemonController.js
- api/models/Box.js
- api/models/Pokemon.js
- api/services/BoxOrdering.js
- test/controller/box.js
- test/controller/pokemon.js
This updates the `POST /p/:id/move` endpoint to also accept an `index` parameter indicating the index at which a Pokémon should be inserted in the box.
Fixes the serverside portion of #20
> Allow a box's contents to be rearranged

- api/controllers/UserController.js
- api/models/User.js
- api/services/Constants.js
- api/services/Validation.js
- config/policies.js
- config/routes.js
- test/controller/user.js
Adds a `POST /editAccountInfo` endpoint that accepts array parameters `friendCodes`, `inGameNames`, and `trainerShinyValues`.
See [the unit tests](/porygonco/porybox/blob/2a0e7cfb811e9095fc9cd71f068f7b92bd35b95a/test/controller/user.js#L187) for examples/validations.
> Add editable account info

- .babelrc
- app.js
- client/.babelrc
The only babel feature that we're actually using serverside is async functions. Everything else now works natively anyway, and we're hurting performance by transpiling it.
The client still uses babel-preset-es2015 for browser compatibility.
> Don't transpile serverside code more than necessary

- api/services/Promise.js
- app.js
Using a service is better because it still allows us to reference it without having to redefine it at the top of every file, but we don't affect other modules that use Promises.
> Avoid polluting the global namespace with bluebird Promise

- api/services/Promise.js
- app.js
- config/env/development.js
So it seems like I missed a few things in PRs #123 and #124.
The first issue is that our tests run from the sails configuration in `test/bootstrap.test.js` whereas our normal configuration is in `app.js`. #123 and #124 modified `app.js`, but they never modified `test/bootstrap.test.js`.
This was a problem because our tests were passing (since the config for them hadn't been changed), but the change actually caused a crash on `npm start` and we didn't notice. #129 updates `test/bootstrap.test.js` to be consistent with `app.js`.
Anyway, this PR fixes those issues. The first is that we were using `Promise.config` (a bluebird feature) in `config/env/development`, which gets loaded before the `Promise` service, so it was throwing a `Promise.config is not a function` error. This was fixed by …
> Prevent sails from crashing on startup

- test/bootstrap.test.js
This is the same as those other two PRs from before (#124 and #125), but I forgot to remove the code from the test start file when I removed it from the `app.js` file.
> Remove unnecessary babel from tests

- client/layout.ejs
Currently, the header bar fails to load on any URI that contains a slash after the domain, e.g. `localhost:1337/p/abcdefabcdef`.
> Load the CSS properly when viewing a page with a complex pathname

- api/controllers/PokemonController.js
- api/services/BoxOrdering.js
- test/controller/auth.js
- test/controller/pokemon.js
- test/controller/user.js
This PR:
* Causes the server to return a 400 error if the client does not specify a box while uploading, as decided in #128
* Fixes all the tests that broke as a result of this change
> Require the client to specify a box on upload (fixes #128)

- api/controllers/BoxController.js
- test/controller/box.js
This adds properties like `speciesName` and `level` to te server's response when viewing a box.
> Send parsed box contents when viewing a box page

- client/pokemon/pokemon.spec.js
Let's make sure we always make PRs for changes, even if they are small ones, even if we are just going to merge them ourselves, so we don't break master.
Anyway, @not-an-aardvark is there any case that these will be undefined except in the tests? Do we want to put a check in for them? I assume there should never be a situation where this occurs, we will always have tid, sid, tsv and esv in the real world?
> Fix pokemon tests

- .travis.yml
- api/controllers/BoxController.js
- api/controllers/PokemonController.js
- api/controllers/UserController.js
- api/models/Box.js
- api/models/Pokemon.js
- api/models/User.js
- api/services/Validation.js
- api/services/catchAsyncErrors.js
- test/controller/box.js
- test/controller/pokemon.js
Fixes #157
tl;dr We should avoid using waterline's `.save()` method for database models, and instead use .update() to make updates to the database. If a document is modified between the time that it is fetched and `.save()` is called, the changes will be overwritten by `.save()` but not by `.update()`.
There is still the possibility of leaving the database in an inconsistent state if connection is randomly lost (which is sort of difficult to avoid since mongo doesn't have transactions), but there shouldn't be any more race condition issues now.
> Fix concurrency issues

- api/controllers/UserController.js
- api/models/Passport.js
- api/services/passport.js
- api/services/protocols/local.js
- client/login/login.ctrl.js
- client/login/login.module.js
- client/login/login.spec.js
- client/login/login.view.html
- test/controller/auth.js
We currently have a bit of Passport.js boilerplate in our authentication code that is supposed to allow for email login, even though we only allow logins with usernames. This caused our API to be inconsistent (e.g. we called a username an "identifier" on login, but a "name" on registration). Also, the code authentication endpoint was overcomplicated.
Anyway, now we explicitly only allow usernames for login.
This PR also refactors some of the boilerplate code from callbacks to use Promises instead.
> Refactor login

- api/models/User.js
- test/controller/user.js
This was allowing anyone to see a user's unlisted boxes in the `_orderedBoxIds` array by going to the `/user/theUsername` endpoint.
> Omit server-only properties from user profile responses

- package.json
Contains a partial fix for #226, although we will also need to change the view a bit.
`expToNextLevel` will now be `Infinity` for things at level 100 (although as far as the client is concerned, it will be `null` because `JSON.stringify(Infinity) === null`).
> Update pk6parse to v0.10.4

- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
- client/pokemon/upload-info.view.html
The upload info with notes is probably too much for its own card on the summary, but not enough to take up a whole tab by itself. So after talking with SP and TSAR, I threw it into an Info icon on the toolbar and moved the Delete option into the Settings menu. 
I also brought back the Analysis tab for just the clone status. It's kind of lonely there, but we could add a "more analysis coming soon" message if we wanted to.
> Add upload info dialog with notes

- package.json
Somehow greenkeeper missed this back in April. Apparently the fixes the internal v8 warnings that were getting logged to the console every time the server was started up.
> Upgrade kerberos to v0.0.21

- api/models/Box.js
- api/models/Pokemon.js
- api/models/User.js
- api/models/UserPreferences.js
- test/controller/box.js
- test/controller/user.js
This poses a small privacy concern, e.g. we don't want other users to know when a user's profile was last updated.
> Don't leak model values such as `createdAt` to clients

- api/controllers/BoxController.js
- api/controllers/PokemonController.js
- api/services/PokemonHandler.js
- client/box/box-list.view.html
- client/box/box.ctrl.js
- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon.ctrl.js
- client/pokemon/pokemon.spec.js
- test/controller/box.js
- test/controller/pokemon.js
Relates to #247
This allows a `pokemonFields` querystring parameter to be used for fetching boxes and Pokémon. It should be useful to reduce the server's response size for large boxes, since we don't actually need all the properties of all the box contents.
e.g.
* `GET /b/abcdef?pokemonFields=id,dexNo,speciesName`
* `GET /p/uvwxyz?pokemonFields=id,dexNo,speciesName`
This also modifies the client to only fetch the fields that are needed.
> Allow box fields to be filtered via querystring

- config/session.js
Previously, all sessions were expiring after 1 day.
> Increase the expiration time for sessions

- client/add/add.ctrl.js
- client/add/add.module.js
- client/add/pokemon.view.html
* Disables the "upload" button if no files are selected
* Adds a "View" button to the toast for when exactly one thing has been uploaded successfully, linking to the uploaded thing. The button does not display if multiple things were uploaded successfully.
* Display different messages depending on how many things were uploaded:
* (if no errors): "25 Pokémon uploaded successfully"
* (if some errors and some success): "10 Pokémon uploaded successfully (15 failed)"
* (if all errors): "Upload failed, no Pokémon uploaded"
> Improve the upload toast

- api/services/BoxOrdering.js
- test/controller/pokemon.js
The `updatedAt` property is a waterline feature, so it wasn't getting used in native queries.
> Fix an issue where the box updatedAt field wasn't getting changed

- api/services/BoxOrdering.js
tl;dr if something is unexpectedly missing from a box list due to database issues, the server will attempt to repair it by adding the item to the end of the list.
> Add sanity checks for database inconsistencies

- client/app.js
fixes #299 
I think the issue is that the modal window promise ends up rejecting if the user cancels the window.
> Don't log errors when users close windows

- client/app.js
- client/layout.ejs
- client/styles/importer.less
This adds a `?v=VERSION` querystring to all requests for templates, which should prevent them from getting loaded from the browser's cache after we update porybox's version number.
> Ensure that templates aren't loaded from cache after bumping the version

- package.json
[Changelog](/porygonco/pk6parse/blob/master/CHANGELOG.md#v01013-2016-07-10)
> * Fixed an issue where Magikarp's data file was incorrectly formatted
* Fixed an issue where certain memories would cause parsing failures
* Fixed an issue where item data for Latiasite/Latiosite was missing
* Fixed an issue where item data for the ORAS "Bike" item was missing
Fixes #326
> Upgrade pk6parse to v0.10.13

- client/app.js
- client/layout.ejs
- client/styles/importer.less
This fixes a bug where weird angular errors that would occur if boxes had certain names.
The bug did not allow full XSS, since angular sandboxes expressions to prevent that. But we should still escape the expressions anyway.
> Use `ng-non-bindable` to escape angular expressions in ejs data

- package.json
[Changelog](/porygonco/pk6parse/blob/master/CHANGELOG.md)
> ## v0.10.15 (2016-07-12)
> * Fixed an issue where some encounter types were missing
> ## v0.10.14 (2016-07-11)
> * Added `hiddenPowerType` and `hiddenPowerPower` keys
> Upgrade pk6parse to v0.10.15

- client/add/add.ctrl.js
- client/app.js
- client/box/box.ctrl.js
- client/login/login.ctrl.js
- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
- client/prefs/prefs.ctrl.js
- client/profile/profile.ctrl.js
- client/userMenu/user.ctrl.js
- config/routes.js
- test/controller/auth.js
- test/controller/box.js
- test/controller/main.js
- test/controller/pokemon.js
- test/controller/user.js
fixes #194
This PR updates the server's API endpoints to be more RESTful, along with adding an `/api/v1` prefix to avoid route conflicts and allow future API changes. It also updates the client and the tests to match these endpoints.
I'm open to any other suggestions anyone might have about making endpoints more RESTful, but I thought we should change this sooner rather than later so that people can start relying on our API.
---
(same as #344 but onto master this time)
> Make API endpoints more RESTful

- config/policies.js
Due to #349, these policies are no longer used.
> Remove unused policies from config/policies.js

- client/add/add.ctrl.js
- client/add/box.ctrl.js
- client/add/pokemon.ctrl.js
- client/box/box-edit.ctrl.js
- client/box/box.ctrl.js
- client/login/login.ctrl.js
- client/pokemon/pokemon-edit.ctrl.js
- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
- client/prefs/prefs.ctrl.js
- client/profile/profile-edit.ctrl.js
- client/profile/profile.ctrl.js
- client/userMenu/user.ctrl.js
- client/userMenu/user.module.js
Given that the client controllers are considered as class constructors by angular, it will save some memory (and performance) to define prototype functions for them rather than redefining the functions for each instance.
> Use prototype functions for client controllers

- client/layout.ejs
In responses from res.forbidden(), the `_csrf` view local is not included (see https://github.com/balderdashy/sails/issues/2566). We had a typeof check to prevent this from causing an error, but that typeof check was invalid.
> Fix the invalid typeof check for the csrf token

- api/controllers/PokemonController.js
- test/controller/pokemon.js
Previously, we weren't escaping nicknames at all when setting the `Content-Disposition` header. This caused Node to throw an error if people set nicknames containing control characters, since we were putting those control characters directly into the header. (It's good that Node threw an error, because if it hadn't, people would have been able to modify the downloaded files themselves if the nickname started with `\r\n`.)
The resulting filenames will still be nonsense if the nicknames contain control characters, (they will be URL-encoded since most filesystems don't handle control characters in filenames very well). But that's fine, since a nickname would probably only contain control characters if it was an intentional attack on the server anyway.
> Escape special characters in nicknames correctly when downloading

- package.json
- test/bootstrap.test.js
- test/controller/auth.js
- test/controller/box.js
- test/controller/main.js
- test/controller/pokemon.js
- test/controller/user.js
- test/test-helpers.js
This PR adds superagent-defaults as a devDependency, which allows custom defaults in request parameters. This means that we can stop disabling the CSRF protection for the tests because it's now possible to set a default `x-csrf-token` header without setting it explicitly for each request.
> Use superagent-defaults for default request parameters in tests

- api/controllers/BoxController.js
- api/services/PokemonHandler.js
- client/app.js
- client/box/box-list.view.html
- client/box/box.ctrl.js
- client/box/box.module.js
- package.json
- test/controller/box.js
- test/controller/pokemon.js
Relates to #345
See https://github.com/porygonco/porybox/issues/345#issuecomment-231894729 for an explanation of why the pagination API needed to be replaced
To do:
> Replace the pagination API

- .eslintrc
- app.js
- client/app.js
- client/login/login.ctrl.js
On the server we should be using `sails.log` instead of `console.log`, and on the client we should be using the `errorHandler` service for error handling anyway.
> Re-add the `no-console` linter rule

- client/account/account.module.js
- client/account/password.ctrl.js
- client/account/password.view.html
- client/login/login.ctrl.js
- client/login/login.module.js
- client/login/login.view.html
- client/login/register.view.html
fixes #197, fixes #360, fixes #391 
The login page now uses toast to display errors, rather than the [odd placeholder line](https://i.gyazo.com/f5e3a496892d12474d215193f01d714e.png) from before. It also adds better clientside validation so that people can notice that there is an error before they submit the form.
> Refactor the login page

- client/static/how-to-pk6-1-bvs.html
- client/static/how-to-pk6-2-homebrew.html
- client/static/how-to-pk6-3-4-save-files.html
Corrected the SD card paths for Battle Videos and game saves, and updated the version requirements for BrowserHax and MenuHax now that versions supporting firmwares up to 11.0.0-33 are out.
> Documentation update

- config/http.js
- test/controller/auth.js
* `X-XSS-Protection: 1; mode=block`: tells browsers not to run certain scripts if it detects that they were created from XSS issues
* `X-Content-Type-Options: nosniff`: Prevents browser from inferring MIME types (see [here](https://msdn.microsoft.com/en-us/library/gg622941(v=vs.85).aspx) for more info)
* `Content-Security-Policy: default-src 'self' ; script-src 'self' 'unsafe-inline' *.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src * ; font-src 'self' https://fonts.gstatic.com; connect-src *; frame-ancestors 'self' ; form-action 'self' ; reflected-xss block;`: Prevents the browser from accessing any resources on different domains, except explicit domains where we allow it. This is used to reduce the effect of an XSS attack if one appeared.
> Add some security headers

- client/box/box-card.view.html
- client/box/box-list.view.html
- client/styles/importer.less
> Add a lock icon for unlisted boxes

- api/controllers/PasswordResetController.js
- api/controllers/UserController.js
- api/models/User.js
- config/local.example.js
- test/controller/passwordReset.js
- test/controller/user.js
Note: This change requires a small database migration. Open your local mongo shell (e.g. `sudo mongo` while the database is running). Then enter `use porybox` to select the database, and run:
```js
db.sessions.find().snapshot().forEach(function(doc) { doc.session = JSON.parse(doc.session); db.sessions.save(doc); })
```
To undo this (e.g. if you want to check out another branch before this PR is merged):
```js
db.sessions.find().snapshot().forEach(function(doc) { doc.session = JSON.stringify(doc.session); db.sessions.save(doc); })
```
> Clear a user's sessions when their password is reset/changed

- api/policies/readOnlyMode.js
- client/app.js
- client/header.ejs
- client/layout.ejs
- client/static/faq.html
- client/styles/importer.less
- config/local.example.js
- config/policies.js
- test/controller/auth.js
* Server returns a 405 response to any non-GET request
* A toast displays on the client when the page loads to notify the user about read-only mode. It also displays if the user attempts to something that's not allowed during read-only mode.
> Add a config option for read-only mode

- package.json
angular-material [doesn't appear to follow semver](https://github.com/angular/material/blob/master/CHANGELOG.md#110-2016-08-14), and they introduced several breaking changes in v1.1.0. We should lock the version to v1.0.x until we figure out how to fix the things that break in the newer version.
> Lock angular-material to v1.0.x

- .eslintrc
- package.json
Also see #506 
tl;dr: We don't need babel-eslint anymore since ESLint supports async/await on its own now.
This PR also removes some unnecessary punctuation from our .eslintrc file.
> Remove babel-eslint

- client/pokemon/pokemon-card.view.html
- client/styles/importer.less
Some things have been rearranged to make room – form names are now always on their own line, and the visibility icon is now at the bottom. Here's the new layout:
No more weird behavior with "sometimes two lines" things like this (original layout):
> Add gender symbols to card view

- api/controllers/PokemonController.js
- api/models/Pokemon.js
- api/services/PokemonHandler.js
- config/policies.js
- config/routes.js
- test/controller/box.js
- test/controller/pokemon.js
This allows a `gen` property to be specified from the multi-upload API, defaulting to 6. The property is passed as an option to pk6parse (which currently doesn't do anything with it), and it's sent as a regular property to the client.
Uploads are only allowed to have a gen that is in the `pk6parse.SUPPORTED_GENS` array, or `[6]` is `pk6parse.SUPPORTED_GENS` doesn't exist (which is the case for the old version of pk6parse). This means that gen 7 uploads are currently not allowed (since someone could upload a file with `gen: 7` that fails future validation checks). To enable them, we should export `SUPPORTED_GENS = [6, 7]` from pk6parse when the parser is ready, which will make the server accept gen 7 uploads.
> Add API support for gen 7

- client/app.js
Fixes #646
They  changed the default from '' to '!'. Easiest way to solve all the problems is just set it back to default.
> Reset the hashbang prefix to ''

- client/app.js
We should fix this properly at some point, but for now, we are fine just to change the config. It will be removed at some point in angular, but I don't think we want to focus on that right now.
Details: https://docs.angularjs.org/guide/migration#commit-bcd0d4
> Fix broken pre-assigned bindings

- client/add/add.ctrl.js
- client/add/add.spec.js
- client/test/mdtoast.js
This adds a progress meter for uploads rather than having the "Uploading" toast bounce up and down repeatedly.
> Fix bouncing upload toast with large uploads (fixes #737)

- client/add/parseSaveFile.js
As a result of this, nothing with a dex number of greater than 750 could be uploaded.
> Remove hardcoded upper bound in save file parsing

- api/controllers/PokemonController.js
- test/controller/pokemon.js
As a potential security issue, this has already been cherry-picked onto production.
> Update the _boxVisibility when moving a pokemon

- client/pokemon/pokemon-card.view.html
- client/pokemon/pokemon-full.view.html
- client/pokemon/pokemon.ctrl.js
Since we decided to keep the gender symbol for both Nidorans in their species' names, this code change prevents the normal blue/pink gender symbol from being displayed in addition to that.
[Screenshot](http://i.imgur.com/507XvJ1.png)
> Removed the redundant gender symbol on Nidoran

- client/static/extracting-pokemon-files.html
- client/static/faq.html
- client/static/how-to-pk6-2-homebrew.html
- client/static/how-to-pk7-1-bvs.html
- client/static/how-to-pk7-2-homebrew.html
- client/static/how-to-pk7-3-digital-save-files.html
Some small fixes for the documentation, mainly focused on making it clear homebrew can be used for save extraction on 11.3.
> Documentation fixes for 11.3

- client/static/extracting-pokemon-files.html
- client/static/how-to-pk6-2-homebrew.html
- client/static/how-to-pk7-2-homebrew.html
- client/static/how-to-pk7-4-tea.html
* Included mention of doodlehax for N3DS users on 11.4
* Updated CFW requirements to note that it is now available for 11.3
* Removed mentions of OoT3D as we don't currently discuss secondary exploits in our documentation
> Updated documentation for 3DS update 11.4
